CREATE SCHEMA interrupciones;

CREATE TABLE INTERRUPCIONES.VISITAS (
  ID_VISITA SERIAL NOT NULL,
  ID_USUARIO INTEGER,
  OBSERVACION TEXT,
  FECHAREGISTRO TIMESTAMP WITH TIME ZONE,
PRIMARY KEY(ID_VISITA));